// The launch social kit as Markdown, for kb/launch/social-kit.md.
// Every line comes from ./launch-beats and ./launch-facts; edit those, not the output.
import { socialBeats } from "@hraness/design-kit/launch"
import { launchBeatFacts, launchSocialKit, launchStatus, resolvedLaunchBeats } from "./launch-beats"

const block = (text: string): string => ["```text", text, "```"].join("\n")
const thread = (name: string, posts: readonly string[]): string[] => [
  `## ${name}`,
  "",
  ...posts.flatMap((post, index) => [`Post ${String(index + 1)} of ${String(posts.length)}, ${String([...post].length)} characters`, "", block(post), ""]),
]

export function renderSocialKitMarkdown(): string {
  return [
    "# Slopcamera launch social kit",
    "",
    "Generated by `bun run launch:kit` in `apps/web/` from `apps/web/src/launch-beats.ts` and `apps/web/src/launch-facts.ts`. Do not edit by hand; change the beats or facts and run it again.",
    "",
    `Posts go out from the @hraness account. The status is "${launchStatus}", a public release, so posts may point people at the install. Each post pairs with the render named for its beat below; the launch film and its square and portrait cuts are in the post. Show HN and the Product Hunt first comment are written by a person from the fact sheet below.`,
    "",
    ...thread("X thread", launchSocialKit.x),
    ...thread("Bluesky thread", launchSocialKit.bluesky),
    ...thread("Threads thread", launchSocialKit.threads),
    "## LinkedIn post",
    "",
    block(launchSocialKit.linkedin),
    "",
    "## Product Hunt",
    "",
    `Tagline: ${launchSocialKit.productHunt.tagline}`,
    "",
    "Description:",
    "",
    block(launchSocialKit.productHunt.description),
    "",
    `Topics: ${launchSocialKit.productHunt.tags.join(", ")}`,
    "",
    "## Show HN and first comment fact sheet",
    "",
    ...launchSocialKit.showHnFacts.map(fact => `- ${fact}`),
    "",
    "## Beats and their visuals",
    "",
    ...socialBeats(resolvedLaunchBeats).map((beat, index) => `${String(index + 1)}. ${beat.headline} (example \`${beat.visual.scene}\`)`),
    "",
    "## Facts and their records",
    "",
    ...Object.entries(launchBeatFacts).map(([name, fact]) => `- ${name}: ${fact.value}. ${fact.source}`),
    "",
  ].join("\n")
}
