import * as stylex from "@stylexjs/stylex"

const tablet = "@media (max-width: 48rem)"
const forcedColors = "@media (forced-colors: active)"

// These recipes own only the /docs document surface: layout, section
// navigation, and generated prose. The ordinary shell and marketing
// presentation remain separate boundaries.
const docs = stylex.create({
  layout: {
    display: "grid",
    gridTemplateColumns: { default: "16rem minmax(0, 1fr)", [tablet]: "minmax(0, 1fr)" },
    columnGap: "clamp(1.5rem, 4vw, 4rem)",
    width: "min(100% - 2 * var(--gutter), 72rem)",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
    paddingTop: "clamp(2rem, 6vw, 4rem)",
    paddingBottom: "clamp(3rem, 8vw, 6rem)",
  },
  nav: {
    display: { default: "block", [tablet]: "none" },
    alignSelf: "start",
    position: { default: "sticky", [tablet]: "static" },
    top: "5rem",
    marginBottom: { default: 0, [tablet]: "2rem" },
    paddingBottom: { default: 0, [tablet]: "1rem" },
    borderBottomWidth: { default: 0, [tablet]: "1px" },
    borderBottomStyle: { default: "none", [tablet]: "solid" },
    borderBottomColor: { default: "transparent", [tablet]: "var(--line)" },
    fontSize: "0.92rem",
  },
  mobileNav: {
    display: { default: "none", [tablet]: "block" },
    minWidth: 0,
    marginBottom: "1.5rem",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--line)",
  },
  navSummary: {
    minHeight: "2.75rem",
    paddingTop: "0.75rem",
    paddingBottom: "0.75rem",
    color: "var(--ink)",
    cursor: "pointer",
    overflowWrap: "anywhere",
    lineHeight: 1.5,
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineColor: { default: "var(--gold)", [forcedColors]: "Highlight" },
    outlineOffset: "4px",
  },
  navContext: {
    display: "block",
    marginTop: "0.25rem",
    color: "var(--muted)",
    fontSize: "0.875rem",
  },
  mobileLinks: {
    paddingTop: "0.75rem",
    paddingBottom: "1rem",
    fontSize: "0.92rem",
  },
  navHome: {
    display: "inline-block",
    marginBottom: "0.85rem",
    color: { default: "var(--ink)", ":hover": "var(--gold)" },
    fontWeight: 600,
    textDecoration: "none",
  },
  navSection: {
    marginTop: "1.1rem",
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
  },
  navSectionLabel: {
    marginBottom: "0.35rem",
    color: "var(--muted)",
    fontSize: "0.9375rem",
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  navList: {
    display: "grid",
    gap: "0.15rem",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    listStyleType: "none",
  },
  navLink: {
    display: "block",
    paddingTop: "0.25rem",
    paddingRight: "0.5rem",
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    marginLeft: "-0.5rem",
    borderRadius: "0.375rem",
    color: { default: "var(--muted)", ":hover": "var(--ink)" },
    textDecoration: "none",
  },
  navLinkCurrent: {
    color: { default: "var(--ink)", ":hover": "var(--ink)" },
    fontWeight: 550,
    backgroundColor: "color-mix(in srgb, var(--gold) 10%, transparent)",
    [forcedColors]: {
      outlineWidth: "1px",
      outlineStyle: "solid",
      outlineColor: "CanvasText",
      backgroundColor: "Canvas",
    },
  },
  article: {
    minWidth: 0,
    maxWidth: "44rem",
  },
  sectionLabel: {
    marginTop: 0,
    marginBottom: "0.75rem",
    color: "var(--gold)",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  heading: {
    marginTop: 0,
    marginBottom: "0.75rem",
    maxWidth: "22ch",
    fontSize: "clamp(2rem, 4.5vw, 3rem)",
    fontWeight: 600,
    letterSpacing: "-0.02em",
    lineHeight: 1.08,
  },
  lede: {
    marginTop: 0,
    marginBottom: "2.25rem",
    maxWidth: "38rem",
    color: "var(--muted)",
    fontSize: "1.125rem",
    lineHeight: 1.55,
  },
  h2: {
    marginTop: "2.5rem",
    marginBottom: "0.75rem",
    fontSize: "1.5rem",
    fontWeight: 600,
    letterSpacing: "-0.01em",
    lineHeight: 1.25,
    scrollMarginTop: "5rem",
  },
  h3: {
    marginTop: "1.9rem",
    marginBottom: "0.5rem",
    fontSize: "1.15rem",
    fontWeight: 600,
    lineHeight: 1.3,
    scrollMarginTop: "5rem",
  },
  p: {
    marginTop: 0,
    marginBottom: "1rem",
    lineHeight: "var(--hraness-reading-leading, 1.7)",
  },
  list: {
    marginTop: 0,
    marginBottom: "1rem",
    paddingLeft: "1.4rem",
    lineHeight: "var(--hraness-reading-leading, 1.7)",
  },
  listItem: {
    marginBottom: "0.3rem",
  },
  link: {
    color: { default: "var(--gold)", ":visited": "var(--gold)" },
    textDecorationColor: "color-mix(in srgb, var(--gold) 45%, transparent)",
    textUnderlineOffset: "0.15em",
  },
  code: {
    overflowWrap: "anywhere",
    paddingTop: "0.08em",
    paddingRight: "0.3em",
    paddingBottom: "0.08em",
    paddingLeft: "0.3em",
    borderRadius: "0.3em",
    backgroundColor: "color-mix(in srgb, var(--ink) 7%, transparent)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.86em",
    [forcedColors]: {
      backgroundColor: "Canvas",
      outlineWidth: "1px",
      outlineStyle: "solid",
      outlineColor: "CanvasText",
    },
  },
  pre: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: "1.25rem",
    marginLeft: 0,
    paddingTop: "0.9rem",
    paddingRight: "1rem",
    paddingBottom: "0.9rem",
    paddingLeft: "1rem",
    overflowX: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--line)",
    borderRadius: "0.625rem",
    backgroundColor: "color-mix(in srgb, var(--ink) 4%, transparent)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    [forcedColors]: {
      backgroundColor: "Canvas",
      borderColor: "CanvasText",
    },
  },
  preCode: {
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: "transparent",
    fontSize: "inherit",
    [forcedColors]: {
      outlineWidth: 0,
      outlineStyle: "none",
    },
  },
  blockquote: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: "1.25rem",
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: "1rem",
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "var(--gold)",
    color: "var(--muted)",
  },
  tableWrap: {
    marginBottom: "1.25rem",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.92rem",
    lineHeight: 1.5,
  },
  th: {
    paddingTop: "0.45rem",
    paddingRight: "1rem",
    paddingBottom: "0.45rem",
    paddingLeft: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "var(--line)",
    fontWeight: 600,
    textAlign: "left",
  },
  td: {
    paddingTop: "0.45rem",
    paddingRight: "1rem",
    paddingBottom: "0.45rem",
    paddingLeft: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "color-mix(in srgb, var(--line) 55%, transparent)",
    textAlign: "left",
    verticalAlign: "top",
  },
  hr: {
    marginTop: "2.5rem",
    marginBottom: "2.5rem",
    borderWidth: 0,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--line)",
  },
  footnote: {
    marginTop: "2.5rem",
    paddingTop: "1rem",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--line)",
    color: "var(--muted)",
    fontSize: "0.9375rem",
    lineHeight: 1.6,
  },
  anchor: {
    color: "inherit",
    textDecoration: "none",
    outlineOffset: "0.15em",
  },
})

export const siteDocsClassNames = {
  layout: stylex.props(docs.layout).className,
  nav: stylex.props(docs.nav).className,
  mobileNav: stylex.props(docs.mobileNav).className,
  navSummary: stylex.props(docs.navSummary).className,
  navContext: stylex.props(docs.navContext).className,
  mobileLinks: stylex.props(docs.mobileLinks).className,
  navHome: stylex.props(docs.navHome).className,
  navSection: stylex.props(docs.navSection).className,
  navSectionLabel: stylex.props(docs.navSectionLabel).className,
  navList: stylex.props(docs.navList).className,
  navLink: stylex.props(docs.navLink).className,
  navLinkCurrent: stylex.props(docs.navLink, docs.navLinkCurrent).className,
  article: stylex.props(docs.article).className,
  sectionLabel: stylex.props(docs.sectionLabel).className,
  heading: stylex.props(docs.heading).className,
  lede: stylex.props(docs.lede).className,
  h2: stylex.props(docs.h2).className,
  h3: stylex.props(docs.h3).className,
  p: stylex.props(docs.p).className,
  list: stylex.props(docs.list).className,
  listItem: stylex.props(docs.listItem).className,
  link: stylex.props(docs.link).className,
  code: stylex.props(docs.code).className,
  pre: stylex.props(docs.pre).className,
  preCode: stylex.props(docs.preCode).className,
  blockquote: stylex.props(docs.blockquote).className,
  tableWrap: stylex.props(docs.tableWrap).className,
  table: stylex.props(docs.table).className,
  th: stylex.props(docs.th).className,
  td: stylex.props(docs.td).className,
  hr: stylex.props(docs.hr).className,
  footnote: stylex.props(docs.footnote).className,
  anchor: stylex.props(docs.anchor).className,
} as const
