import * as stylex from "@stylexjs/stylex"

const tablet = "@media (max-width: 48rem)"
const phone = "@media (max-width: 34rem)"
const forcedColors = "@media (forced-colors: active)"

// These recipes own only the ordinary document shell. Homepage marketing,
// install/copy recipes and the framework-neutral appearance menu are separate.
const shell = stylex.create({
  skip: {
    position: "fixed",
    top: "0.75rem",
    left: "0.75rem",
    zIndex: 100,
    paddingTop: "0.7rem",
    paddingRight: "1rem",
    paddingBottom: "0.7rem",
    paddingLeft: "1rem",
    borderRadius: "0.625rem",
    transform: { default: "translateY(-180%)", ":focus": "translateY(0)" },
    backgroundColor: "var(--ink)",
    backgroundImage: "none",
    backgroundPosition: "initial",
    backgroundSize: "auto auto",
    backgroundRepeat: "repeat",
    backgroundAttachment: "scroll",
    backgroundOrigin: "padding-box",
    backgroundClip: "border-box",
    color: "var(--paper)",
    fontWeight: 500,
    textDecoration: "none",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 40,
    display: "flex",
    minHeight: "3.5rem",
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: "0.75rem",
    columnGap: "1.5rem",
    flexWrap: { default: "nowrap", [tablet]: "wrap" },
    paddingTop: { default: 0, [tablet]: "0.6rem" },
    paddingRight: "max(var(--gutter), calc((100% - 72rem) / 2))",
    paddingBottom: { default: 0, [tablet]: "0.6rem" },
    paddingLeft: "max(var(--gutter), calc((100% - 72rem) / 2))",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: { default: "var(--hraness-material-outline, transparent)", [forcedColors]: "CanvasText" },
    boxShadow: { default: "var(--hraness-material-rest, 0 4px 20px color-mix(in srgb, var(--ink) 5%, transparent))", [forcedColors]: "none" },
    backgroundColor: "var(--hraness-material-chrome-paint, color-mix(in srgb, var(--paper) 84%, transparent))",
    backgroundImage: "none",
    backgroundPosition: "initial",
    backgroundSize: "auto auto",
    backgroundRepeat: "repeat",
    backgroundAttachment: "scroll",
    backgroundOrigin: "padding-box",
    backgroundClip: "border-box",
    backdropFilter: "var(--hraness-material-chrome-blur, blur(14px) saturate(1.4))",
  },
  wordmark: {
    minHeight: "2.75rem",
    fontSize: "1rem",
    fontWeight: 600,
    letterSpacing: "-0.01em",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
  },
  brandMark: {
    width: "1.375rem",
    height: "1.375rem",
    marginRight: "0.5rem",
  },
  actions: {
    display: { default: "flex", [tablet]: "contents" },
    minWidth: 0,
    alignItems: "center",
    rowGap: "0.75rem",
    columnGap: "1rem",
  },
  navigation: {
    display: "flex",
    flexWrap: "nowrap",
    overflowX: "auto",
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: { default: "1.35rem", [tablet]: "1rem", [phone]: "0.85rem" },
    // Keep the wordmark and appearance trigger together above navigation.
    order: { default: 0, [tablet]: 3 },
    width: { default: "auto", [tablet]: "100%" },
    marginLeft: { default: 0, [phone]: "auto" },
  },
  navigationLink: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "2.75rem",
    flexShrink: 0,
    color: { default: "var(--muted)", ":hover": "var(--ink)" },
    fontSize: "0.92rem",
    fontWeight: 500,
    textDecoration: "none",
  },
  homeNavigationLink: {
    // Keep every destination available in the scrollable phone navigation.
    display: "inline-flex",
  },
  primaryAction: {
    display: "inline-flex",
    minHeight: "var(--hraness-marketing-action-height)",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.45rem",
    paddingTop: "0.6rem",
    paddingRight: "1.1rem",
    paddingBottom: "0.6rem",
    paddingLeft: "1.1rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--hraness-marketing-accent)",
      ":hover": "color-mix(in oklch, var(--hraness-marketing-accent) 84%, black)",
    },
    borderImageSource: "none",
    borderImageSlice: "100%",
    borderImageWidth: 1,
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderRadius: "var(--hraness-marketing-radius)",
    backgroundColor: {
      default: "var(--hraness-marketing-accent)",
      [forcedColors]: {
        default: "CanvasText",
        ":hover": "color-mix(in oklch, var(--hraness-marketing-accent) 84%, black)",
      },
      ":hover": "color-mix(in oklch, var(--hraness-marketing-accent) 84%, black)",
    },
    backgroundImage: "none",
    backgroundPosition: "initial",
    backgroundSize: "auto auto",
    backgroundRepeat: "repeat",
    backgroundAttachment: "scroll",
    backgroundOrigin: "padding-box",
    backgroundClip: "border-box",
    color: "var(--gold-ink)",
    fontFamily: "var(--hraness-marketing-text-font)",
    fontSize: "0.95rem",
    fontWeight: 500,
    lineHeight: 1.2,
    textDecoration: "none",
  },
  navigationAction: {
    minHeight: "2.75rem",
    flexShrink: 0,
    paddingTop: "0.4rem",
    paddingRight: "0.9rem",
    paddingBottom: "0.4rem",
    paddingLeft: "0.9rem",
    color: { default: "var(--gold-ink)", ":hover": "var(--ink)" },
    fontSize: "0.9rem",
    marginLeft: { default: 0, [tablet]: "auto" },
  },
})

export const siteShellClassNames = {
  skip: stylex.props(shell.skip).className,
  header: stylex.props(shell.header).className,
  wordmark: stylex.props(shell.wordmark).className,
  brandMark: stylex.props(shell.brandMark).className,
  actions: stylex.props(shell.actions).className,
  navigation: stylex.props(shell.navigation).className,
  navigationLink: stylex.props(shell.navigationLink).className,
  homeNavigationLink: stylex.props(shell.navigationLink, shell.homeNavigationLink).className,
  navigationAction: stylex.props(shell.primaryAction, shell.navigationAction).className,
} as const
