import { lstat, realpath } from "node:fs/promises"
import { basename, dirname, extname, join, resolve } from "node:path"
import sharp from "sharp"
import { generateSlopcameraProviderImage, validateSlopcameraProviderImageInput, type GenerateSlopcameraProviderImageInput, type SlopcameraImageProviderDependencies } from "./image-provider.js"
import { publishSlopcameraRetainedFile as publish } from "./retained-file.js"
import { SlopcameraCloudError } from "./cloud-errors.js"

async function assertAbsent(path: string) {
  try { await lstat(path) } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return
    throw error
  }
  throw new Error(`Refusing to overwrite an existing output: ${path}`)
}
/** A retained, no-retry file attempt for an explicitly selected direct vendor. */
export async function generateSlopcameraProviderImageFile(request: GenerateSlopcameraProviderImageInput & { readonly outputPath: string }, dependencies: SlopcameraImageProviderDependencies = {}) {
  validateSlopcameraProviderImageInput(request)
  const input = { ...request, ...(request.references === undefined ? {} : { references: request.references.map(reference => ({ ...reference, bytes: Uint8Array.from(reference.bytes) })) }) }
  if (typeof input.outputPath !== "string" || input.outputPath.length < 1 || input.outputPath.length > 4096 || input.outputPath.includes("\0")) throw new Error("Output path must be a bounded file path.")
  const outputPath = join(await realpath(dirname(resolve(input.outputPath))), basename(input.outputPath))
  const extension = extname(outputPath).toLowerCase()
  const format = extension === ".png" ? "png" : extension === ".jpg" || extension === ".jpeg" ? "jpeg" : extension === ".webp" ? "webp" : undefined
  if (format === undefined) throw new Error("Image output must end in .png, .jpg, .jpeg, or .webp.")
  await assertAbsent(outputPath)
  for (const suffix of [".receipt.json", ".request.json", ".failure.json", ".generated.png", ".generated.jpg", ".generated.webp"]) await assertAbsent(`${outputPath}${suffix}`)
  // The immutable request file prevents accidental resubmission under the same identity.
  await publish(`${outputPath}.request.json`, `${JSON.stringify({ provider: input.provider, model: input.model, prompt: input.prompt, resolution: input.resolution, aspectRatio: input.aspectRatio, status: "prepared", automaticRetry: false }, null, 2)}\n`)
  try {
    const image = await generateSlopcameraProviderImage(input, dependencies)
    const sourceExtension = image.mediaType === "image/png" ? "png" : image.mediaType === "image/jpeg" ? "jpg" : "webp"
    const source = await publish(`${outputPath}.generated.${sourceExtension}`, image.bytes)
    const decoded = sharp(image.bytes, { limitInputPixels: 64_000_000, failOn: "error" })
    const metadata = await decoded.metadata()
    if ((metadata.pages ?? 1) !== 1) throw new Error("Generated image must contain one frame.")
    const bytes = await decoded.toFormat(format).toBuffer()
    const artifact = await publish(outputPath, bytes)
    const receipt = { ...artifact, outputPath, source, provider: image.provider, model: image.model, requestId: image.requestId, warnings: image.warnings, mediaType: `image/${format}`, status: "completed", automaticRetry: false }
    await publish(`${outputPath}.receipt.json`, `${JSON.stringify(receipt, null, 2)}\n`)
    return receipt
  } catch (error) {
    await publish(`${outputPath}.failure.json`, `${JSON.stringify({ status: "failed-or-ambiguous", automaticRetry: false, requestPath: `${outputPath}.request.json`, code: error instanceof SlopcameraCloudError ? error.code : null, diagnostic: error instanceof SlopcameraCloudError ? error.message : "Local transport or output failed." })}\n`)
    throw new Error(`Image attempt failed or may have been charged. Inspect ${outputPath}.request.json and retained generated bytes before a new attempt.`)
  }
}
